version: '3.4'
  
networks:
  web:
    external:
      name: web
services:
  api:
    labels:
      - 'traefik.backend=cutting-ui'
      - 'traefik.port=4044'
      - 'traefik.frontend.rule=Host:reports.valleycuttingsystems.net'
    networks:
      web:
    image: wayimp/cutting-ui
    ports:
      - 4044:4044